on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Allow pushing to `master` branch which is protected
          # See https://github.com/settings/tokens/1477019585
          token: ${{ secrets.GIT_PUSH_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npx auto-npm-version
        env:
          # Allow creating a new entry in https://github.com/taskworld/positioning-strategy/releases
          GITHUB_TOKEN: ${{ secrets.GIT_PUSH_TOKEN }}
          # Allow publishing to https://www.npmjs.com/package/positioning-strategy
          # See https://www.npmjs.com/settings/rebasecop/tokens
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
